#!/bin/bash
user="denis"
GREEN='\033[0;32m'
RED='\033[0;31m'
GRAY='\033[0;30m'
RESET='\033[0m'

echo -e "${GREEN}Setup sudo and add new user${RESET}"
pacman -S sudo
EDITOR=nano visudo
echo Defaults env_reset >> /etc/sudoers
echo Defaults editor=/usr/bin/nano, !env_editor >> /etc/sudoers
echo "Create $user user and change password of him"
useradd -m $user
passwd $user

usermod -aG wheel $user

echo -e "You need uncomment ${GRAY}#%wheel ALL=(ALL:ALL) ALL${RESET} in ${GRAY}/etc/sudoers"${RESET}
