#!/bin/bash
user="denis"

echo -e "Setup sudo and add new user"
pacman -S sudo
EDITOR=nano visudo
echo Defaults env_reset >> /etc/sudoers
echo Defaults editor=/usr/bin/nano, !env_editor >> /etc/sudoers
echo "Create $user user and change password of him"
useradd -m $user
passwd $user

usermod -aG wheel $user

echo "You need uncomment #%wheel ALL=(ALL:ALL) ALL in /etc/sudoers"
echo "Enter visudo"
